name: Deploy to Render and Notify Discord

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deploy Hook
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"

      - name: Notify Discord - Deploy Triggered
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d '{"content":"已觸發 Render 部署，等一下回傳結果。"}' \
            "${{ secrets.DISCORD_WEBHOOK_URL }}"

      - name: Check Render Deploy Status
        run: |
          sleep 20
          RESPONSE=$(curl -s -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys)
          STATUS=$(echo "$RESPONSE" | jq -r '.[0].status')
      
          echo "Latest deploy status: $STATUS"
      
          if [ "$STATUS" = "live" ]; then
            curl -H "Content-Type: application/json" \
                 -X POST \
                 -d '{"content":"🟢 Render 部署成功！"}' \
                 ${{ secrets.DISCORD_WEBHOOK_URL }}
          else
            curl -H "Content-Type: application/json" \
                 -X POST \
                 -d "{\"content\":\"🔴 Render 部署失敗，狀態：$STATUS\"}" \
                 ${{ secrets.DISCORD_WEBHOOK_URL }}
          fi
