name: Deploy to Render and Notify Discord

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deploy Hook
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"

      - name: Notify Discord - Deploy Triggered
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d '{"content":"已觸發 Render 部署，等一下回傳結果。"}' \
            "${{ secrets.DISCORD_WEBHOOK_URL }}"
